name: Deploy to dev
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: "json-extended"
          webhook_url: ${{ secrets.WEBHOOK_URL_DEV }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
